import './global.css';
import {TYPES,KINDS,demo,balances,money,qty,position,today,monthRange,calculate,normalizeRef,periodSummary} from './ledger.js';
import {db,loadData,rpc,upload,documentUrl,createAccount} from './data.js';
import {parseDocument,DEFAULT_MAP} from './pdf-parser.js';
let data=demo(),isDemo=true,view='dashboard',period=today().slice(0,7),search='',filter='',draft=null,importData=null,busy=false;
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const admin=()=>data.profile.role==='admin';
const nav=[['dashboard','Vue d’ensemble'],['journal','Journal des mouvements'],['pdf','Importer un PDF'],['reports','Rapports'],['opening','Report initial'],['recovery','Reprise du classeur',true],['accounts','Gestion des comptes',true],['mapping','Articles PDF',true],['audit','Traçabilité',true]];
const button=(label,action,extra='',cls='')=>'<button type="button" class="'+cls+'" data-action="'+action+'" '+extra+'>'+label+'</button>';
const field=(label,name,type='text',value='',extra='')=>'<label><span>'+label+'</span><input name="'+name+'" type="'+type+'" value="'+h(value)+'" '+extra+'></label>';
const select=(label,name,options,value)=>'<label><span>'+label+'</span><select name="'+name+'">'+options.map(([v,l])=>'<option value="'+h(v)+'" '+(v===value?'selected':'')+'>'+h(l)+'</option>').join('')+'</select></label>';
const footer=(label='Enregistrer')=>'<div class="error hidden" id="form-error" role="alert"></div><footer>'+button('Annuler','close')+'<button class="primary" type="submit">'+label+'</button></footer>';
function notify(message){const t=document.querySelector('#toast');t.textContent=message;t.style.display='block';setTimeout(()=>t.style.display='none',5500);}
function close(){if(busy)return;if(draft?.url)URL.revokeObjectURL(draft.url);draft=null;modal.close();modal.innerHTML='';}
function open(title,content){modal.innerHTML='<div class="card-head"><h2>'+h(title)+'</h2>'+button('Fermer','close')+'</div>'+content;modal.showModal();}
function fail(error){const e=document.querySelector('#form-error');if(e){e.textContent=error.message||String(error);e.classList.remove('hidden');}else notify(error.message||String(error));}
async function refresh(){if(!isDemo)data=await loadData();render();}
const valueOf=m=>(m.lines||[]).reduce((n,l)=>n+Number(l.delta)*Number(l.unit_price),0);
function positionTable(rows){return '<div class="table-wrap"><table><thead><tr><th>Emballage</th><th class="num">Quantité signée</th><th class="num">Prix unitaire</th><th class="num">Valeur</th><th>Situation</th></tr></thead><tbody>'+rows.map(t=>'<tr><td>'+t.label+'</td><td class="num">'+qty(t.quantity)+'</td><td class="num">'+money(t.price)+'</td><td class="num '+(t.value<0?'good':t.value>0?'bad':'')+'">'+money(t.value)+'</td><td>'+position(t.quantity)+'</td></tr>').join('')+'</tbody><tfoot><tr><td colspan="3">Position nette valorisée</td><td class="num">'+money(rows.reduce((n,t)=>n+t.value,0))+'</td><td>'+position(rows.reduce((n,t)=>n+t.value,0))+'</td></tr></tfoot></table></div>';}
function journalTable(ops){if(!ops.length)return '<div class="empty">Aucun mouvement dans cette sélection.</div>';return '<div class="table-wrap"><table><thead><tr><th>Date</th><th>Nature</th><th>Référence</th><th>Source</th><th class="num">Impact initial</th><th>État</th><th></th></tr></thead><tbody>'+ops.map(m=>'<tr><td>'+h(m.date||'À vérifier')+'</td><td>'+h(KINDS[m.kind])+'</td><td>'+h(m.ref)+'</td><td>'+h({manual:'Manuel',pdf:'PDF',workbook:'Classeur'}[m.source])+'</td><td class="num">'+money(valueOf(m))+'</td><td><span class="badge '+(m.cancel_date?'warn':'')+'">'+(m.cancel_date?'Annulée le '+h(m.cancel_date):'Enregistrée')+'</span></td><td>'+button('Détails','detail','data-id="'+h(m.id)+'"','linkbtn')+'</td></tr>').join('')+'</tbody></table></div>';}
function dashboard(){const rows=balances(data),total=rows.reduce((n,t)=>n+t.value,0);return '<div class="headline"><div><div class="eyebrow">Brasimba × Rivinter</div><h2>Une position globale, documentée</h2></div>'+button('＋ Nouveau mouvement','new','','gold')+'</div>'+(!data.opening.date?'<div class="banner">Le report initial n’a pas de date confirmée. Le solde global inclut toutes les écritures reprises ; les rapports datés et les nouvelles saisies attendent cette confirmation.</div>':'')+'<div class="metrics"><article class="metric feature"><div class="eyebrow">Solde global valorisé</div><div class="val">'+money(total)+'</div><div class="mini">'+position(total)+'</div></article><article class="metric"><div class="eyebrow">Mouvements</div><div class="val">'+data.operations.length+'</div><div class="mini">Historique conservé</div></article><article class="metric"><div class="eyebrow">Justificatifs PDF</div><div class="val">'+data.operations.filter(m=>m.document_path).length+'</div><div class="mini">Accès privé et signé</div></article><article class="metric"><div class="eyebrow">Dates à vérifier</div><div class="val">'+data.operations.filter(m=>!m.date).length+'</div><div class="mini">Incluses dans le global</div></article></div><section class="card"><div class="card-head"><h2>Position par Bremer</h2><span class="sub">Négatif : Brasimba doit · Positif : Rivinter doit</span></div>'+positionTable(rows)+'</section><section class="card"><div class="card-head"><h2>Derniers mouvements</h2>'+button('Tout consulter','nav','data-view="journal"','linkbtn')+'</div>'+journalTable([...data.operations].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,8))+'</section>';}
function journal(){const ops=data.operations.filter(m=>(!filter||m.kind===filter)&&(!search||(m.ref+' '+m.note+' '+(m.date||'')).toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>(b.date||'').localeCompare(a.date||''));return '<div class="toolbar"><div class="actions"><input id="search" aria-label="Rechercher une référence" placeholder="Référence, date ou note…" value="'+h(search)+'">'+select('Nature','filter',[['','Toutes les natures'],...Object.entries(KINDS)],filter)+'</div>'+button('＋ Mouvement','new','','gold')+'</div><section class="card">'+journalTable(ops)+'</section>';}
function monthlyTable(start,end){const rows=periodSummary(data,start,end);return '<section class="card"><div class="card-head"><h2>Résumé et écart du mois</h2><span class="sub">Quantités nettes des contrepassations</span></div><div class="table-wrap"><table><thead><tr><th>Bremer</th><th class="num">Livraisons</th><th class="num">Retours</th><th class="num">Écart livraison − retour</th><th class="num">Tous débits</th><th class="num">Tous crédits</th><th class="num">Variation nette</th></tr></thead><tbody>'+rows.map(t=>'<tr><td>'+t.label+'</td><td class="num">'+qty(t.delivery)+'</td><td class="num">'+qty(t.returned)+'</td><td class="num">'+qty(t.gap)+'</td><td class="num">'+qty(t.debit)+'</td><td class="num">'+qty(t.credit)+'</td><td class="num">'+qty(t.net)+'</td></tr>').join('')+'</tbody></table></div><div class="card-body explain">L’écart compare uniquement livraisons et retours. La variation nette inclut aussi les consignations payantes, bouteilles, casses, pertes et contrepassations.</div></section>';}
function reports(){const {start,end}=monthRange(period),undated=data.operations.filter(m=>!m.date).length;return '<div class="toolbar"><label>Mois<input type="month" id="period" value="'+period+'"></label><div class="actions">'+button('Exporter CSV','csv')+button('Imprimer / PDF','print')+'</div></div>'+(!data.opening.date?'<div class="banner">Confirmez la date du report initial avant de produire un rapport mensuel.</div>':(undated?'<div class="banner">Rapport partiel : '+undated+' écritures sans date sont exclues du mois et du solde daté. Consultez le dashboard pour la position globale complète.</div>':'')+monthlyTable(start,end)+'<section class="card"><div class="card-head"><h2>Position datée au '+end+'</h2></div>'+positionTable(balances(data,end,false))+'</section><section class="card"><div class="card-head"><h2>Mouvements du mois</h2></div>'+journalTable(data.operations.filter(m=>m.date>=start&&m.date<=end))+'</section><section class="card"><div class="card-head"><h2>Contrepassations du mois</h2><span class="sub">Impact opposé à l’écriture d’origine</span></div>'+journalTable(data.operations.filter(m=>m.cancel_date>=start&&m.cancel_date<=end))+'</section>');}
function opening(){return '<div class="headline"><h2>Solde Brasimba initial</h2><span class="badge">'+(data.opening.locked?'Verrouillé':'Déverrouillé')+'</span></div><p>Report global signé, indépendant de tout dépôt. Date confirmée : <strong>'+h(data.opening.date||'Non confirmée')+'</strong>.</p><section class="card">'+positionTable(TYPES.map(t=>({...t,quantity:data.opening.quantities[t.id]||0,value:(data.opening.quantities[t.id]||0)*t.price})))+'</section>'+(admin()?'<div class="actions">'+button(data.opening.locked?'Déverrouiller':'Verrouiller','lock')+button('Modifier les soldes / la date','edit-opening',data.opening.locked?'disabled':'','gold')+'</div>':'')+'<details class="note"><summary>Informations d’origine conservées</summary><pre>'+h(JSON.stringify(data.opening.source_metadata||{},null,2))+'</pre></details>';}
function recovery(){return '<section class="card"><div class="card-head"><h2>Reprise fidèle du classeur</h2></div><div class="card-body"><p>Importer le fichier JSON de reprise fourni séparément. Les quantités historiques sont conservées telles quelles, sans appliquer rétroactivement les nouvelles règles.</p><div class="banner">Réservé à un compte neuf. Aucune donnée existante n’est écrasée. Ne publiez pas ce fichier privé sur GitHub.</div><label>Fichier de reprise JSON<input id="recovery-file" type="file" accept=".json,application/json"></label><div id="recovery-preview"></div></div></section>';}
function accounts(){return '<div class="headline"><h2>Comptes autorisés</h2>'+button('Créer un compte','account-new','','gold')+'</div><section class="card"><div class="table-wrap"><table><thead><tr><th>Nom</th><th>Email</th><th>Rôle</th><th>Accès</th><th></th></tr></thead><tbody>'+data.profiles.map(p=>'<tr><td>'+h(p.full_name)+'</td><td>'+h(p.email)+'</td><td>'+h(p.role)+'</td><td>'+(p.active?'Actif':'Désactivé')+'</td><td>'+(p.id!==data.profile.id?button('Modifier','account-edit','data-id="'+h(p.id)+'"'):'Votre compte')+'</td></tr>').join('')+'</tbody></table></div></section><p class="explain">Les utilisateurs consultent et encodent. Les administrateurs gèrent les comptes, la reprise, le report initial, les correspondances et les annulations. Les écritures enregistrées ne se suppriment pas.</p>';}
function mapping(){return '<div class="headline"><h2>Correspondance des articles de livraison</h2>'+button('Ajouter / modifier','mapping-new','','gold')+'</div><div class="banner">Les codes non reconnus restent à vérifier : aucune quantité inconnue n’est comptabilisée automatiquement.</div><section class="card"><div class="table-wrap"><table><thead><tr><th>Code Brasimba</th><th>Désignation</th><th>Bremer</th></tr></thead><tbody>'+data.mappings.map(m=>'<tr><td>'+h(m.code)+'</td><td>'+h(m.label)+'</td><td>'+h(TYPES.find(t=>t.id===m.bremer_id)?.label)+'</td></tr>').join('')+'</tbody></table></div></section>';}
function audit(){return '<section class="card"><div class="card-head"><h2>Journal d’audit</h2></div><div class="table-wrap"><table><thead><tr><th>Horodatage</th><th>Action</th><th>Compte</th><th>Détail</th></tr></thead><tbody>'+[...data.audit].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(a=>'<tr><td>'+h(a.created_at)+'</td><td>'+h(a.action)+'</td><td>'+h(data.profiles.find(p=>p.id===a.actor_id)?.full_name||a.actor_id)+'</td><td><details><summary>Afficher</summary><pre>'+h(JSON.stringify(a.details,null,2))+'</pre></details></td></tr>').join('')+'</tbody></table></div></section>';}
function pdfPage(){return '<section class="card"><div class="card-head"><h2>Lire un bon Brasimba</h2><span class="badge">PDF + OCR en français</span></div><div class="card-body"><p>Insérez un bon de consignation / livraison ou de déconsignation. Le document sera lu sur cet appareil. Vérifiez la proposition avant tout enregistrement.</p><label>Document PDF · 15 Mo maximum · 10 pages maximum<input id="pdf-file" type="file" accept=".pdf,application/pdf"></label><p id="pdf-progress" role="status"></p><div class="note">Un seul bon par fichier. Les bouteilles retournées sont converties en casiers complets, avec contrôle des bacs pour éviter le double comptage. Les pages manquantes et les lectures incertaines sont signalées.</div></div></section>';}
function render(){const visible=nav.filter(n=>!n[2]||admin());if(!visible.some(n=>n[0]===view))view='dashboard';app.innerHTML='<div class="layout"><aside class="sidebar"><div class="brand"><img src="/logo-rivinter.png" alt="Rivinter"><strong>RIVINTER SARLU</strong><small>COMPTE EMBALLAGES GLOBAL</small></div><nav class="nav">'+visible.map(n=>button(n[1],'nav','data-view="'+n[0]+'"',view===n[0]?'active':'')).join('')+'</nav><div class="sidefoot"><strong>'+h(data.profile.full_name)+'</strong>'+h(isDemo?'Démonstration':data.profile.role)+'</div></aside><main class="main"><header class="topbar"><h1>'+visible.find(n=>n[0]===view)[1]+'</h1><div class="filters">'+button('Actualiser','refresh')+button('Mot de passe','password')+button(isDemo?'Connexion':'Déconnexion','logout')+'</div><select class="mobile-nav" aria-label="Navigation">'+visible.map(n=>'<option value="'+n[0]+'" '+(view===n[0]?'selected':'')+'>'+n[1]+'</option>').join('')+'</select></header><div class="content"><div class="print-head"><h1>RIVINTER · Compte emballages</h1><p>Période : '+h(period)+'</p></div>'+(isDemo?'<div class="banner">DÉMONSTRATION · Données fictives, saisies temporaires, aucune connexion à votre base.</div>':'')+({dashboard,journal,pdf:pdfPage,reports,opening,recovery,accounts,mapping,audit}[view])()+'</div></main></div>';}
function operationForm(kind='delivery',pdf=null,file=null){
 draft={request_id:crypto.randomUUID(),pdf,file,url:file?URL.createObjectURL(file):null};
 open(pdf?'Vérifier le document avant encodage':'Nouveau mouvement','<form id="operation-form">'+(pdf?'<iframe title="Justificatif à vérifier" class="pdf-preview" src="'+h(draft.url)+'"></iframe>'+pdf.warnings.map(w=>'<div class="banner">'+h(w)+'</div>').join('')+'<details><summary>Texte et lignes reconnus</summary><pre>'+h(pdf.text)+'</pre><pre>'+h(JSON.stringify(pdf.details,null,2))+'</pre></details>':'')+'<div class="formgrid">'+select('Nature','kind',Object.entries(KINDS).filter(([k])=>k!=='legacy'&&(!pdf||['delivery','return'].includes(k))),kind)+field('Date du mouvement','date','date',pdf?.date||today(),'required max="'+today()+'"')+field('N° BL, bon ou BV','ref','text',pdf?.ref||'','required maxlength="120"')+field('Montant BV (payante / bouteilles)','bv_amount','number','','min="0" step="1"')+'</div><p id="units" class="note"></p><div class="formgrid">'+TYPES.map(t=>field(t.label,'q_'+t.id,'number',pdf?.rows.find(r=>r.bremer_id===t.id)?.quantity||0,'required min="0" max="10000000" step="1"')).join('')+'</div><div id="impact" class="note"></div><label><span>Motif / vérifications (obligatoire pour casse, perte ou avertissement PDF)</span><textarea name="note" maxlength="4000"></textarea></label><label class="check"><input type="checkbox" name="reviewed" required> Je confirme la nature, la date, la référence et chaque quantité après vérification.</label>'+footer(pdf?'Valider et conserver le PDF':'Enregistrer')+'</form>');updateImpact();
}
function formRows(form){return TYPES.map(t=>({bremer_id:t.id,quantity:Number(form.elements['q_'+t.id].value)}));}
function updateImpact(){const f=document.querySelector('#operation-form');if(!f)return;const kind=f.elements.kind.value,auto=['bottles','breakage'].includes(kind);f.elements.q_BAC.disabled=auto;if(auto)f.elements.q_BAC.value=0;
 document.querySelector('#units').textContent=kind==='bottles'?'Saisissez des BOUTEILLES : multiples de 12 (65 cl), 20 (50 cl) ou 24 (33 / 30 cl). Les casiers sont crédités et les bacs associés débités.':kind==='breakage'?'Saisissez des ÉQUIVALENTS CASIERS de bouteilles cassées ou manquantes, et non des bouteilles isolées. Les bacs récupérés sont crédités automatiquement. Pour perdre aussi le bac, utilisez « Perte emballage complet ».':'Saisissez des CASIERS COMPLETS. La ligne Bacs représente uniquement des bacs seuls, jamais les bacs déjà compris dans les casiers.';
 try{const c=calculate(kind,formRows(f));document.querySelector('#impact').textContent='Impact global : '+money(c.value)+(c.bv?' · Montant BV attendu : '+money(c.bv):'');}catch(e){document.querySelector('#impact').textContent=e.message;}
}
function detail(id){const m=data.operations.find(x=>x.id===id);if(!m)return;open('Mouvement '+m.ref,'<div class="card-body"><p>'+h(KINDS[m.kind])+' · '+h(m.date||'Date à vérifier')+' · '+h(m.source)+'</p>'+positionTable(TYPES.map(t=>({...t,quantity:m.lines.find(l=>l.bremer_id===t.id)?.delta||0,value:(m.lines.find(l=>l.bremer_id===t.id)?.delta||0)*t.price})))+'<p>'+h(m.note)+'</p>'+(m.cancel_date?'<div class="banner">Annulée le '+h(m.cancel_date)+' : '+h(m.cancel_reason)+'. L’écriture d’origine est conservée.</div>':'')+'<div class="actions">'+(m.document_path?button('Ouvrir le justificatif','document','data-id="'+h(id)+'"'):'')+(admin()&&!m.cancel_date?button('Annuler par contrepassation','cancel','data-id="'+h(id)+'"'):'')+'</div><details><summary>Données originales / extraction</summary><pre>'+h(JSON.stringify(m.metadata||{},null,2))+'</pre></details></div>');}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(){if(!data.opening.date)throw Error('Confirmez la date du report.');const {start,end}=monthRange(period);const rows=[['Date','Nature','Référence','Source','Événement',...TYPES.flatMap(t=>[t.id+' débit',t.id+' crédit']),'Valeur Fc']];for(const m of data.operations){if(!m.date)continue;for(const [date,sign,event] of [[m.date,1,'Origine'],[m.cancel_date,-1,'Contrepassation']])if(date&&date>=start&&date<=end)rows.push([date,KINDS[m.kind],m.ref,m.source,event,...TYPES.flatMap(t=>{const q=(m.lines.find(l=>l.bremer_id===t.id)?.delta||0)*sign;return [Math.max(q,0),Math.max(-q,0)];}),valueOf(m)*sign]);}download('rivinter-'+period+'.csv','\uFEFF'+rows.map(r=>r.map(c=>'"'+String(c).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');}
function login(){app.innerHTML='<main class="login"><section class="card"><img src="/logo-rivinter.png" alt="Rivinter"><div class="eyebrow">Compte emballages global</div><h1>Bienvenue chez Rivinter</h1><p>Une application indépendante, un compte Brasimba global.</p>'+(!db?'<div class="banner">Démonstration disponible. Configurez votre nouveau projet Supabase pour activer les comptes et la conservation des données.</div>':'')+'<form id="login-form">'+field('Email','email','email','','required autocomplete="username"')+field('Mot de passe','password','password','','required autocomplete="current-password"')+'<div class="error hidden" id="form-error" role="alert"></div><button class="gold" type="submit" '+(!db?'disabled':'')+'>Se connecter</button></form><p>'+button('Explorer la démonstration','demo')+'</p></section></main>';}
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||busy)return;const action=b.dataset.action;try{
 if(action==='nav'){view=b.dataset.view;render();}
 if(action==='close')close();
 if(action==='refresh')await refresh();
 if(action==='new')operationForm();
 if(action==='demo'){data=demo();data.mappings=Object.entries(DEFAULT_MAP).map(([code,bremer_id])=>({code,bremer_id,label:'Article de démonstration'}));isDemo=true;render();}
 if(action==='logout'){if(db&&!isDemo)await db.auth.signOut();data=demo();isDemo=true;login();}
 if(action==='detail')detail(b.dataset.id);
 if(action==='print'){if(!data.opening.date)throw Error('Confirmez la date du report.');window.print();}
 if(action==='csv')csv();
 if(action==='document'){const m=data.operations.find(x=>x.id===b.dataset.id),url=await documentUrl(m.document_path);window.open(url,'_blank','noopener,noreferrer');}
 if(action==='cancel'){const id=b.dataset.id;close();open('Annuler sans supprimer','<form id="cancel-form" data-id="'+h(id)+'">'+field('Date de contrepassation','date','date',today(),'required max="'+today()+'"')+field('Motif obligatoire','reason','text','','required minlength="3" maxlength="4000"')+footer('Confirmer l’annulation')+'</form>');}
 if(action==='lock'){open(data.opening.locked?'Déverrouiller le report':'Verrouiller le report','<form id="lock-form">'+field('Motif obligatoire','reason','text','','required minlength="3"')+footer('Confirmer')+'</form>');}
 if(action==='edit-opening'){if(data.opening.locked)throw Error('Déverrouillez le report.');open('Modifier le report initial','<form id="opening-form"><div class="banner">Cette modification affecte le solde global. Les anciennes valeurs restent dans l’audit.</div>'+field('Date confirmée du report','date','date',data.opening.date||'','required max="'+today()+'"')+'<div class="formgrid">'+TYPES.map(t=>field(t.label+' · solde signé',t.id,'number',data.opening.quantities[t.id]||0,'required step="1"')).join('')+'</div>'+field('Motif obligatoire','reason','text','','required minlength="3"')+footer()+'</form>');}
 if(action==='recover'){if(!importData)throw Error('Choisissez un fichier.');open('Confirmer la reprise historique','<form id="recovery-form"><p>'+importData.operations.length+' écritures seront reprises dans le nouveau compte. Aucune écriture existante ne sera remplacée.</p><label class="check"><input type="checkbox" required> Je confirme la reprise de ce classeur dans cette nouvelle application.</label>'+footer('Importer une seule fois')+'</form>');}
 if(action==='account-new')open('Créer un compte','<form id="account-form">'+field('Nom complet','full_name','text','','required minlength="2" maxlength="120"')+field('Email','email','email','','required')+field('Mot de passe temporaire','password','password','','required minlength="12" autocomplete="new-password"')+select('Rôle','role',[['user','Utilisateur'],['admin','Administrateur']],'user')+footer('Créer le compte')+'</form>');
 if(action==='account-edit'){const p=data.profiles.find(p=>p.id===b.dataset.id);open('Modifier '+p.full_name,'<form id="profile-form" data-id="'+h(p.id)+'">'+select('Rôle','role',[['user','Utilisateur'],['admin','Administrateur']],p.role)+select('Accès','active',[['true','Actif'],['false','Désactivé']],String(p.active))+footer()+'</form>');}
 if(action==='mapping-new')open('Correspondance article','<form id="mapping-form">'+field('Code article','code','text','','required pattern="[0-9]{4,6}"')+field('Libellé','label','text','','required minlength="2"')+select('Famille','bremer',TYPES.map(t=>[t.id,t.label]),'ALE50')+footer()+'</form>');
 if(action==='password'){if(isDemo)throw Error('Connectez-vous à votre compte réel.');open('Changer mon mot de passe','<form id="password-form">'+field('Nouveau mot de passe','password','password','','required minlength="12" autocomplete="new-password"')+footer()+'</form>');}
 }catch(e){fail(e);}});
document.addEventListener('input',e=>{if(e.target.closest('#operation-form'))updateImpact();});
document.addEventListener('change',async e=>{try{
 if(e.target.id==='search'){search=e.target.value;render();}
 if(e.target.name==='filter'){filter=e.target.value;render();}
 if(e.target.id==='period'){period=e.target.value||today().slice(0,7);render();}
 if(e.target.matches('.mobile-nav')){view=e.target.value;render();}
 if(e.target.id==='recovery-file'){const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('Fichier JSON trop volumineux.');importData=null;const p=JSON.parse(await file.text());if(p.format!=='rivinter-workbook-v1'||!Array.isArray(p.operations)||!p.opening?.quantities)throw Error('Format de reprise non reconnu.');importData=p;const rows=balances({opening:{...p.opening,date:null},operations:p.operations});document.querySelector('#recovery-preview').innerHTML='<p>'+p.operations.length+' écritures · '+p.operations.filter(m=>!m.date).length+' dates absentes · Report initial à dater.</p>'+positionTable(rows)+button('Lancer la reprise','recover','','gold');}
 if(e.target.id==='pdf-file'){const file=e.target.files[0];if(!file)return;busy=true;e.target.disabled=true;const progress=document.querySelector('#pdf-progress');try{const {readPdf}=await import('./pdf-reader.js');const pdf=await readPdf(file,Object.fromEntries(data.mappings.map(m=>[m.code,m.bremer_id])),message=>progress.textContent=message);if(pdf.blocked)throw Error('Plusieurs bons dans ce PDF : séparez les documents avant import.');if(data.operations.some(m=>!m.cancel_date&&(m.pdf_sha256===pdf.hash||(m.kind===pdf.kind&&normalizeRef(m.ref)===normalizeRef(pdf.ref)&&pdf.ref))))throw Error('Ce bon ou ce PDF est déjà enregistré.');busy=false;operationForm(pdf.kind||'delivery',pdf,file);}finally{busy=false;e.target.disabled=false;progress.textContent='';e.target.value='';}}
 }catch(error){fail(error);}});
document.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const f=event.target,v=Object.fromEntries(new FormData(f));busy=true;const submit=f.querySelector('[type="submit"]');if(submit)submit.disabled=true;try{
 if(f.id==='login-form'){const r=await db.auth.signInWithPassword({email:v.email,password:v.password});if(r.error)throw r.error;data=await loadData();isDemo=false;view='dashboard';render();}
 else if(f.id==='operation-form'){const rows=formRows(f),result=calculate(v.kind,rows);if(['paid','bottles'].includes(v.kind)&&Number(v.bv_amount)!==result.bv)throw Error('Montant BV attendu : '+money(result.bv));if((['breakage','loss'].includes(v.kind)||draft.pdf?.warnings.length)&&v.note.trim().length<3)throw Error('Précisez le motif et les vérifications effectuées.');
 const p={request_id:draft.request_id,kind:v.kind,date:v.date,ref:v.ref,rows,bv_amount:v.bv_amount===''?null:Number(v.bv_amount),note:v.note,source:draft.pdf?'pdf':'manual',reviewed:!!v.reviewed,metadata:draft.pdf?{warnings:draft.pdf.warnings,original_ref:draft.pdf.ref,original_date:draft.pdf.date,details:draft.pdf.details,recognized_amount:draft.pdf.source_amount,pages:draft.pdf.pages,expected_pages:draft.pdf.expectedPages,ocr:draft.pdf.ocr,confidence:draft.pdf.confidence}:{}};
 if(!data.opening.date)throw Error('Confirmez d’abord la date du report initial.');if(v.date<data.opening.date||v.date>today())throw Error('Date incompatible avec le report ou dans le futur.');if(data.operations.some(m=>!m.cancel_date&&m.kind===p.kind&&normalizeRef(m.ref)===normalizeRef(p.ref)))throw Error('Cette référence est déjà enregistrée.');
 if(isDemo)data.operations.push({...p,id:p.request_id,lines:result.lines,created_at:new Date().toISOString()});else{if(draft.file){draft.uploadedPath ||= await upload(draft.file,draft.request_id);p.document_path=draft.uploadedPath;p.pdf_sha256=draft.pdf.hash;}await rpc('rg_post',{p});}}
 else if(f.id==='cancel-form'){if(isDemo){const m=data.operations.find(x=>x.id===f.dataset.id);if(m.date&&v.date<m.date)throw Error('Date antérieure au mouvement.');Object.assign(m,{cancel_date:v.date,cancel_reason:v.reason});}else await rpc('rg_cancel',{p_id:f.dataset.id,p_date:v.date,p_reason:v.reason});}
 else if(f.id==='lock-form'||f.id==='opening-form'){const editing=f.id==='opening-form',p={p_date:editing?v.date:data.opening.date,p_quantities:editing?Object.fromEntries(TYPES.map(t=>[t.id,Number(v[t.id])])):data.opening.quantities,p_locked:editing?false:!data.opening.locked,p_revision:data.opening.revision,p_reason:v.reason};if(isDemo){if(editing&&data.operations.some(m=>m.date&&m.date<p.p_date))throw Error('Date postérieure à des mouvements.');Object.assign(data.opening,{date:p.p_date,quantities:p.p_quantities,locked:p.p_locked,revision:data.opening.revision+1});}else await rpc('rg_save_opening',p);}
 else if(f.id==='recovery-form'){if(isDemo)throw Error('La reprise réelle nécessite la connexion à votre nouveau projet Supabase.');await rpc('rg_import_workbook',{p:importData});importData=null;view='dashboard';}
 else if(f.id==='mapping-form'){if(isDemo){data.mappings=data.mappings.filter(m=>m.code!==v.code);data.mappings.push({code:v.code,label:v.label,bremer_id:v.bremer});}else await rpc('rg_save_mapping',{p_code:v.code,p_type:v.bremer,p_label:v.label});}
 else if(f.id==='profile-form'){if(isDemo)throw Error('Connectez-vous à votre base pour gérer des comptes réels.');await rpc('rg_set_profile',{p_id:f.dataset.id,p_role:v.role,p_active:v.active==='true'});}
 else if(f.id==='account-form'){if(isDemo)throw Error('La création de comptes nécessite Vercel et votre nouveau projet Supabase.');await createAccount(v);}
 else if(f.id==='password-form'){const r=await db.auth.updateUser({password:v.password});if(r.error)throw r.error;}
 busy=false;close();if(f.id!=='login-form')await refresh();notify(isDemo?'Démonstration mise à jour (non conservée).':'Opération terminée.');
 }catch(e){fail(e);}finally{busy=false;if(submit)submit.disabled=false;}});
modal.addEventListener('cancel',e=>{e.preventDefault();close();});
async function boot(){if(db){const {data:s}=await db.auth.getSession();if(s.session){try{data=await loadData();isDemo=false;render();return;}catch(e){login();fail(e);return;}}login();}else render();}
const lifecycle=new AbortController();
if(document.modelContext?.registerTool){for(const tool of [
 {name:'read_global_packaging_balance',description:'Lire la position globale affichée du compte connecté ou de démonstration.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(Object.keys(input||{}).length)throw Error('Aucun paramètre attendu.');if(!document.querySelector('.layout'))throw Error('Connexion requise.');return {demonstration:isDemo,balances:balances(data),undated:data.operations.filter(m=>!m.date).length};}},
 {name:'start_packaging_movement',description:'Ouvrir le formulaire visible, sans enregistrer de mouvement. L’utilisateur doit vérifier et valider.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['delivery','return','paid','bottles','breakage','loss']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length!==1||!KINDS[input.kind]||input.kind==='legacy')throw Error('Nature invalide.');if(busy||modal.open||!document.querySelector('.layout'))throw Error('Interface indisponible.');operationForm(input.kind);return {staged:true,saved:false};}}
])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
boot();
